### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by tryller** [RixzZ/firefox_scrollbar_fix#1]
This is for changing firefox scroll bars color?
how to use?

**Comment by RixzZ** [comment]
Is a tweak for Firefox on W10. I just have it on my GitHub to get it quickly. Originally got from here:

- https://www.reddit.com/r/firefox/comments/7f6kc4/floating_scrollbar_finally_possible_in_firefox_57/

It changes the appereance of the scrollbars making them semitransparent, slim and grey (something like the ones from MacOS).

You can install it adding the 'chrome' folder under the Firefox profile folder. For remove it just delete the folder (caution if your 'chrome' folder already existed before).

Restart is needed to apply.
